# Generated by Django 4.0 on 2021-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título')),
                ('start', models.CharField(blank=True, default='2021-12-11T22:29:00', max_length=20, null=True, verbose_name='Data Inicio')),
                ('end', models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Final')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Google Meet')),
            ],
        ),
    ]
