# Generated by Django 4.0 on 2021-12-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='test',
            field=models.DateTimeField(blank=True, null=True, verbose_name='test'),
        ),
    ]
