# Generated by Django 4.0 on 2021-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0002_calendar_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='test',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Inicio'),
        ),
    ]
