# Generated by Django 4.0 on 2021-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0003_remove_calendar_test_alter_calendar_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Data Inicio'),
        ),
    ]
