# Generated by Django 4.0 on 2021-12-11 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0005_alter_calendar_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Inicio'),
        ),
    ]
