# Generated by Django 4.0 on 2021-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0006_alter_calendar_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Google Meet'),
        ),
    ]
