# Generated by Django 4.0 on 2021-12-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0007_alter_calendar_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calendar',
            new_name='Event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
