# Generated by Django 4.0 on 2021-12-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0008_rename_calendar_event_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default='11-12-2021T20:48:24', null=True, verbose_name='Data Inicio'),
        ),
    ]
